yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(
        max_length=200,
        unique=True,
        db_index=True,
        verbose_name="URL"
    )
    description = models.TextField(blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        blank=False,
        help_text='Введите текст',
        verbose_name='Текст'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        blank=False,
        help_text='Введите текст комментария',
        verbose_name='Текст',
    )

    class Meta:
        ordering = ['-pub_date']


class Follow(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following'
            )
        ]
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Контент мэйкер'
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .app_settings import POSTS_PER_PAGE
from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def pagination(obj_list, request):
    paginator = Paginator(obj_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {'page_obj': page_obj}


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    context = pagination(Post.objects.all(), request)
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    context = {'group': group}
    context.update(pagination(group.posts.all(), request))
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    posts_count = post_list.count()
    user = request.user
    following = (user.is_authenticated and Follow.objects.filter(
        user=user, author=author).exists())
    template = 'posts/profile.html'
    context = {
        'author': author,
        'post_list': post_list,
        'post_count': posts_count,
        'following': following,
    }
    context.update(pagination(post_list, request))
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    posts_count = post.author.posts.count()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'posts_count': posts_count,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        request.FILES or None
    )
    if not form.is_valid():
        return render(request, template, {'form': form})
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    template = 'posts/create_post.html'
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    authors = user.follower.values_list('author', flat=True)
    posts = Post.objects.filter(author__id__in=authors)
    context = pagination(posts, request)
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
        return redirect('posts:profile', username=username)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.get(user=user, author__username=username).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
    <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}
      <div class="form-group mb-2">
        {{ form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
{% endif %}
{% for comment in comments %}
<div class="card mb-3 mt-1 shadow-sm">
  <div class="media mb-4">
    <div class="media-body">
      <div class="card-body">
        <strong class="d-block text-gray-dark">
          <p>
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.get_full_name }}
            </a>
          </p>
        </strong>
        <p class="card-text">
          <p>
            {{ comment.text }}
          </p>
          <p>
            <small class="text-muted">
              Дата публикации: {{ comment.pub_date }}
            </small>
          </p>
        </p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block main %}
  <div class="card-body">
    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group row my-3 p-3">
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          {% if field.field.required %}
          <span class="required text-danger" >*</span>
          {% endif %}
        </label>
        {{ field }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
      {% endfor %}
      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">
          {% if is_edit %}
            Сохранить
          {% else %}
            Добавить
          {% endif %}
        </button>
      </div>
    </form>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Посты избранных контент мэйкеров{% endblock %}
{% block main %}
  {% include 'includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    {% include 'posts/post.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block header %}
  #{{ group.title}}
{% endblock %}
{% block main %}
{% for post in page_obj %}
  {% if forloop.first %}
    Посты группы: #{{ group.title }}
    <p>{{ group.description }}</p>
  {% endif %}
  {% include 'posts/post.html' %}
  {% if not forloop.last %}
    <hr>
  {% endif %}
{% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block main %}
  {% include 'includes/switcher.html' with index=True %}
  {% for post in page_obj %}
    {% include 'posts/post.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/post.html
<div class="card mb-3 mt-1 shadow-sm">
{% load thumbnail %}
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}">
{% endthumbnail %}
  <div class="card-body">
    <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
      <strong class="d-block text-gray-dark">@{{ post.author.get_full_name }}</strong>
    </a>
    <p class="card-text">
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.group %}
        <a class="card-link muted" href="{% url 'posts:group_list' post.group.slug %}">
          <strong class="d-block text-gray-dark">
            #{{ post.group.title }}
          </strong>
        </a>
    {% endif %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group ">
        <div class="btn-group ">
          {% if post.comments.exists %}
            <a class="btn btn-sm text-muted" href="{% url 'posts:post_detail' post.id %}#comments" role="button">
              {{ post.comments.count }} комментариев
            </a>
          {% endif %}
          {% if user.is_authenticated %}
            <a class="btn btn-sm text-muted" href="{% url 'posts:add_comment' post.id %}" role="button">
              Добавить комментарий
            </a>
            {% if user == post.author %}
              <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' post.id %}" role="button">Редактировать</a>
            {% else %}
              <a class="btn btn-sm text-muted" href="{% url 'posts:post_detail' post.id %}" role="button">Открыть запись</a>
            {% endif %}
          {% endif %}
        </div>
    </div>
    <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block main %}
<div class="row">
  <aside clss="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ posts_count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
</div>
{% include 'posts/post.html' %}
{% include 'posts/comments.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block main %}
{% for post in page_obj %}
<div class="container py-5">
  <div class="mb-5">
  {% if forloop.first %}
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ post_count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
  </div>
  <article>
    <ul>
      <li>
        Автор: {{ author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    <a href="{% url 'posts:post_detail' post.pk %}">
      подробная информация
    </a>
  </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы {{ post.group.slug }}
      </a>
    {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
</div>
{% endfor %}
{% endblock %}